import { createClient } from "@supabase/supabase-js"
import type { Database } from "../types/supabase" // Assuming you have a types/supabase.ts generated by Supabase CLI

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
const supabaseServiceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY!

// Client-side Supabase client (for public data or RLS-protected user data)
export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey)

// Server-side Supabase client (for admin operations, bypasses RLS)
export const supabaseAdmin = createClient(supabaseUrl, supabaseServiceRoleKey, {
  auth: {
    autoRefreshToken: false,
    persistSession: false,
  },
})

// Functions for Documents
export async function getDocuments(userId: string) {
  const { data, error } = await supabase
    .from("documents")
    .select("*")
    .eq("user_id", userId)
    .order("uploaded_at", { ascending: false })
  if (error) throw error
  return data
}

export async function uploadDocument(userId: string, file: File) {
  const filePath = `${userId}/${Date.now()}-${file.name}`
  const { data: uploadData, error: uploadError } = await supabase.storage
    .from("documents") // Ensure you have a bucket named 'documents'
    .upload(filePath, file, {
      cacheControl: "3600",
      upsert: false,
    })

  if (uploadError) throw uploadError

  const { data, error } = await supabase
    .from("documents")
    .insert({
      user_id: userId,
      file_name: file.name,
      file_type: file.type,
      file_size: file.size,
      storage_path: uploadData.path,
    })
    .select()
    .single()

  if (error) throw error
  return data
}

export async function deleteDocument(documentId: string, storagePath: string) {
  const { error: dbError } = await supabase.from("documents").delete().eq("id", documentId)

  if (dbError) throw dbError

  const { error: storageError } = await supabase.storage.from("documents").remove([storagePath])

  if (storageError) throw storageError
}

// Functions for Data Records
export async function getDataRecords(userId: string, recordType?: string) {
  let query = supabase.from("data_records").select("*").eq("user_id", userId).order("created_at", { ascending: false })

  if (recordType) {
    query = query.eq("record_type", recordType)
  }

  const { data, error } = await query
  if (error) throw error
  return data
}

export async function createDataRecord(userId: string, recordType: string, data: Record<string, any>) {
  const { data: newRecord, error } = await supabase
    .from("data_records")
    .insert({ user_id: userId, record_type: recordType, data: data })
    .select()
    .single()
  if (error) throw error
  return newRecord
}

export async function updateDataRecord(recordId: string, updates: Partial<Record<string, any>>) {
  const { data, error } = await supabase.from("data_records").update(updates).eq("id", recordId).select().single()
  if (error) throw error
  return data
}

export async function deleteDataRecord(recordId: string) {
  const { error } = await supabase.from("data_records").delete().eq("id", recordId)
  if (error) throw error
}
